{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "scp.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - smart-portal.digital
      secretName: smart-portal-digital-tls
  rules:
    - host: smart-portal.digital
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "scp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
