apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-queue-service.fullname" . }}
  labels:
    {{- include "rest-queue-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rest-queue-service.selectorLabels" . | nindent 4 }}
